#!/bin/bash

# needed for elasticsearch
sysctl -w vm.max_map_count=262144

# get docker-compose
curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

# get zammad
mkdir -p /opt/
cd /opt
git clone https://github.com/zammad/zammad-docker-compose.git
cd /opt/zammad-docker-compose

docker-compose up -d
docker network connect aqua zammad-docker-compose_zammad-nginx_1
